namespace ConvertToByte.DAL
{
    public class HistoricoParcela
    {
        public string TipoArquivo { get; set; }
        public string DataReferenciaExtracao { get; set; }
        public string IdentificacaoContrato { get; set; }
        public string TipoRegistroContrato { get; set; }
        public string DataAmortizacaoParcela { get; set; }
        public string NumeroParcelaContrato { get; set; }
        public string Sinal0 { get; set; }
        public string ValorAmortizacaoParcela { get; set; }
        public string Sinal1 { get; set; }
        public string ValorJurosParcela { get; set; }
        public string Sinal2 { get; set; }
        public string ValorSeguroMIPParcela { get; set; }
        public string Sinal3 { get; set; }
        public string ValorSeguroDFIParcela { get; set; }
        public string Sinal4 { get; set; }
        public string ValorTarifaParcela { get; set; }
        public string CodigoEstipulanteMIP { get; set; }
        public string RegiaoApoliceMIP { get; set; }
        public string MatriculaMIP { get; set; }
        public string AgenciaMIP { get; set; }
        public string EmpreendimentoMIP { get; set; }
        public string CodigoApoliceAtualContratoMIP { get; set; }
        public string CodigoEstipulanteDFI { get; set; }
        public string RegiaoApoliceDFI { get; set; }
        public string MatriculaDFI { get; set; }
        public string AgenciaDFI { get; set; }
        public string EmpreendimentoDFI { get; set; }
        public string CodigoApoliceAtualContratoDFI { get; set; }
        public string Sinal5 { get; set; }
        public string ValorAmortizacaoParcelaCorrigida { get; set; }
        public string Sinal6 { get; set; }
        public string ValorJurosParcelaCorrigida { get; set; }
        public string Sinal7 { get; set; }
        public string ValorSeguroMIPParcelaCorrigida { get; set; }
        public string Sinal8 { get; set; }
        public string ValorSeguroDFIParcelaCorrigida { get; set; }
        public string Sinal9 { get; set; }
        public string ValorIOFSeguroMIP { get; set; }
        public string Sinal10 { get; set; }
        public string ValorIOFSeguroDFI { get; set; }
        public string Sinal11 { get; set; }
        public string ValorTarifaParcelaCorrigidaTSA { get; set; }
        public string Sinal12 { get; set; }
        public string ValorAbatimentoFGTSDAMP3 { get; set; }
        public string FatorCorrecaoMonetariaAplicada { get; set; }
        public string Sinal13 { get; set; }
        public string ValorCorrecaoMonetariaEncargos { get; set; }
        public string Sinal14 { get; set; }
        public string ValorJurosRemuneratorios { get; set; }
        public string Sinal15 { get; set; }
        public string ValorJurosMoratorios { get; set; }
        public string Sinal16 { get; set; }
        public string ValorCorrecaoMonetariaAtraso { get; set; }
        public string Sinal117 { get; set; }
        public string ValorIncrementoDescontoOriginal { get; set; }
        public string Sinal18 { get; set; }
        public string ValorIncrementoDescontoCorrigido { get; set; }
        public string Sinal19 { get; set; }
        public string ValorRDM { get; set; }
        public string Sinal20 { get; set; }
        public string SaldoAmortizado { get; set; }
        public string NumeroBoleto { get; set; }
        public string IndicativoParcelaPaga { get; set; }
        public string DataMovimentoPagamento { get; set; }
        public string DataProcessamentoPagamento { get; set; }
        public string FormaLiquidacao { get; set; }
        public string Sinal21 { get; set; }
        public string ValorPago { get; set; }
        public string Sinal22 { get; set; }
        public string ValorDescontoConcedido { get; set; }
        public string ValorDiferencaProximaParcela { get; set; }
        public string Sinal23 { get; set; }
        public string ValorPrincipalSaldoDevedor { get; set; }
        public string ValorJurosSaldoDevedor { get; set; }
        public string Sinal24 { get; set; }
        public string ValorCMSaldoDevedor { get; set; }
        public string CodigoTipoOcorrência { get; set; }
        public string Sinal25 { get; set; }
        public string ValorOcorrencia { get; set; }
        public string IndicadorParcelaEmitida { get; set; }
        public string SistemaAmortizacao { get; set; }
        public string TaxaJurosEfetivoContrato { get; set; }
        public string TaxaJurosNominalContrato { get; set; }
        public string Filler { get; set; }

    }
}
